all:
  hosts:
    server:
      ansible_host: 192.168.11.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/server/virtualbox/private_key
    client:
      ansible_host: 192.168.11.103
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/client/virtualbox/private_key
backup_servers:
  hosts:
    server:
backup_clients:
  hosts:
    client:
      backup_folder: /etc
      backup_prefix: client-etc