---
- hosts: all
  become: yes
  roles:
    - general_settings
- hosts: backup_clients
  become: yes
  roles:
    - backup_client
- hosts: backup_servers
  become: yes
  roles:
    - backup_server
- hosts: backup_clients
  become: yes
  roles:
    - borg_autobackup