- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started
- name: Install EPEL repo
  ansible.builtin.yum:
    name: epel-release
    state: installed
# - name: Update ca-certificates
#   ansible.builtin.yum:
#     name: ca-certificates
#     state: latest
